---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-jan17-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-jan17-3 
  name: chatbot-jan17-3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi